# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -load Itcl" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.
#
#  Copyright 2002-2004 Mayo Foundation.  All Rights Reserved
#  $Id: pkgIndex.tcl,v 1.8 2004/07/20 14:51:55 techenti Exp $
#
package ifneeded gui 2.0 "
 namespace eval gui { }
 set gui::LIBRARY \"$dir\"
 [list source [file join $dir style.tcl]]
 [list source [file join $dir gui.tcl]]
 [list source [file join $dir gui_build.tcl]]
 [list source [file join $dir gui_canvas.itcl]]
 [list source [file join $dir canvas_functions.tcl]]
 [list source [file join $dir gui_elements.tcl]]
 [list source [file join $dir gui_help.tcl]]
 [list source [file join $dir gui_initialize.tcl]]
 [list source [file join $dir gui_xmission.tcl]]
 [list source [file join $dir splash.tcl]]
"
