# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -load Itcl" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.
#
#  Copyright 2002-2004 Mayo Foundation.  All Rights Reserved.
#  $Id: pkgIndex.tcl,v 1.7 2004/07/22 18:40:31 techenti Exp $

package ifneeded bem 1.0 "
if { [info exists ::starkit::topdir] } {
    set ::env(BEM_LIBRARY) \"[file join [file dirname $::argv0] bin $::tcl_platform(os)]\"
} else {
    [list set ::env(BEM_LIBRARY) $dir]
}
 [list source [file join $dir bem.tcl]]
 [list source [file join $dir bem_gpge.itcl]]
 [list source [file join $dir bem_graphs.itcl]]
 [list source [file join $dir bem_welement.itcl]]
 [list source [file join $dir bem_iterate.tcl]]
 [list source [file join $dir bem_parameters.tcl]]
 [list source [file join $dir bem_sweep.tcl]]
"
