# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -load Itcl" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.
#
#  Copyright 2001-2004 Mayo Foundation.  All Rights Reserved.
#  $Id: pkgIndex.tcl,v 1.4 2004/02/09 18:56:00 techenti Exp $

package ifneeded csdl 1.0.1 "
    set env(CSDL_LIBRARY) \"$dir\"
    [list source [file join $dir csdl.tcl]]
    [list source [file join $dir csdl_shapes.itcl]]
    [list source [file join $dir csdl_llcsdl.itcl]]
    [list source [file join $dir csdl_hlcsdl.itcl]]
"





