#! /bin/sh
#
#  bootstrap
#
#  Short script to create basic autoconf/automake configuration
#  files.  Useful when freshly checking out the source tree.

echo "Clearing all cached configuration files"
rm -rf autom4te.cache aclocal.m4
rm -f config.* configure
rm -f Makefile.in depcomp install-sh missing mkinstalldirs

echo "Running aclocal"
aclocal

echo "Running automake"
automake --add-missing --copy

echo "Running autoconf"
autoconf



